---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-precise
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list:
  - "recipe[apt]"
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

suites:
- name: default
  run_list:
  - "recipe[devpi::server]"
  attributes: {}
- name: supervisor
  run_list:
  - "recipe[supervisor-daemon::install]"
  - "recipe[devpi::server]"
  - "recipe[devpi::supervisor]"
  attributes: {}
- name: runit
  run_list:
  - "recipe[devpi::server]"
  - "recipe[devpi::runit]"
  attributes: {}
