---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-14.04
  run_list:
  - "recipe[apt]"
- name: centos-6.4

suites:
- name: server
  run_list:
  - "recipe[devpi::nginx]"
  - "recipe[devpi::server]"
  - "recipe[supervisor-daemon::install]"
  attributes: {}
- name: runit
  run_list:
  - "recipe[devpi::runit]"
  - "recipe[devpi::nginx]"
  attributes: {}
- name: client
  run_list:
  - "recipe[devpi::client]"
  attributes: {}
