---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  run_list:
  - "recipe[apt]"
- name: centos-6.4

suites:
- name: default
  run_list:
  - "recipe[devpi::server]"
  attributes: {}
- name: supervisor
  run_list:
  - "recipe[supervisor-daemon::install]"
  - "recipe[devpi::supervisor]"
  attributes: {}
- name: runit
  run_list:
  - "recipe[devpi::runit]"
  attributes: {}
- name: nginx
  run_list:
  - "recipe[devpi::runit]"
  - "recipe[devpi::nginx]"
  attributes: {}
