source 'https://rubygems.org'

gem 'chef', '~>11.6'
gem 'chefspec', '~>3.0'
gem 'berkshelf', '~>2.0'
gem 'foodcritic', '~>3.0'
gem 'guard', '~>1.8'
gem 'guard-kitchen', '~>0.0'
gem 'guard-rspec', '~>3.1'
gem 'guard-shell', '~>0.5'
gem 'kitchen-vagrant', '~>0.12'
gem 'rspec', '~>2.14'
gem 'tailor', '~>1.3'
gem 'test-kitchen', '~>1.0'
